before_script:
  - source ~/.rvm/scripts/rvm
  - export LANG=en_US.UTF-8
stages:
  - build

build_kmcvstab_demo:
  stage: build
  script:
    - cd demo
    - pod install
    - xcodebuild -workspace *.xcwork* -scheme KMCVStabDemo -quiet
  tags:
    - ios
